CREATE TABLE SalesEntry (
	SalesId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	DateofSale DATE,
	ProductID INTEGER UNSIGNED NOT NULL,
	ItemsSold INTEGER UNSIGNED NOT NULL,
	SaleAmount INTEGER UNSIGNED NOT NULL,
PRIMARY KEY(SalesId));

CREATE TABLE ProductTable (
	ProductID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	ProductName VARCHAR(50),
PRIMARY KEY(ProductID));